### PR TITLE
Use the updated yarn from our berry fork branch pnp-support-absolute-paths-to-nix-store-3.2.1

### PR DESCRIPTION
**Pull request by arijoon**
Currently functional and in use via this branch: https://github.com/rhinofi/launch-deversifi/tree/devops/rhinofi-fork-yarn-3.2.1-update

### CODE REVIEW

**Comment by adrian-gierakowski** [comment]
You can run:

 nix-build --keep-failed

to retain the tmp build dir so that you can inspect the logs

Did our fork work before merging with upstream?

**Comment by arijoon** [comment]
> You can run:
> 
> nix-build --keep-failed
> 
> to retain the tmp build dir so that you can inspect the logs
> 
> Did our fork work before merging with upstream?

It worked, if you generate the `yarn.lock` file with it, but the pnp file genrated by it did not work outside nix env for me and caused many errors by the IDE. Unfortunate part was that it genrated a different `yarn.lock` file to the `yarn-berry` we currently have

**Comment by adrian-gierakowski** [comment]
> did not work outside nix env

You mean outside nix-shell or nix build sandbox?

**Comment by arijoon** [comment]
> You mean outside nix-shell or nix build sandbox?

I meant outside nix-build, as in our yarn fork would cause errors when running scripts directly from the shell

**Comment by arijoon** [comment]
The issue is now resolved, it was due to missing build steps. The `pnp` file and the `hook.js` required separate manual recompilation

**Review by adrian-gierakowski — APPROVED** [review]

**Pull request merged**
